from elasticsearch import Elasticsearch

# Password for the 'elastic' user generated by Elasticsearch
ELASTIC_PASSWORD = "<password>"

# Found in the 'Manage Deployment' page
CLOUD_ID = "deployment-name:dXMtZWFzdDQuZ2Nw..."

# Create the client instance
client = Elasticsearch(
    cloud_id=CLOUD_ID,
    http_auth=("elastic", ELASTIC_PASSWORD)
)

# Define the index name
index_name = 'json_database'

# Create the index (if not already exists)
if not client.indices.exists(index=index_name):
    client.indices.create(index=index_name)

# JSON database example
database = [
    {
        "id": 1,
        "title": "Document 1",
        "content": "This is the content of document 1."
    },
    {
        "id": 2,
        "title": "Document 2",
        "content": "This is the content of document 2."
    },
    {
        "id": 3,
        "title": "Document 3",
        "content": "This is the content of document 3."
    }
]

# Index documents in Elasticsearch
for doc in database:
    client.index(index=index_name, body=doc)

# Refresh the index to make the documents searchable
client.indices.refresh(index=index_name)

# Perform a search query
search_query = {
    "query": {
        "match": {
            "content": "content"
        }
    }
}

# Execute the search query
search_results = client.search(index=index_name, body=search_query)

# Print the search results
print("Search Results:")
for hit in search_results['hits']['hits']:
    print(f"Document ID: {hit['_id']}")
    print(f"Score: {hit['_score']}")
    print(f"Title: {hit['_source']['title']}")
    print(f"Content: {hit['_source']['content']}")
    print()
